/project/:
  get:
    tags:
      - "Project"
    summary: "مشاهده تمام پروژه ها"
    parameters:
      - in: query
        name: page
        required: false
        example: 1
        description: "شماره صفحه"
        type: integer
      - in: query
        name: all
        required: false
        description: "Get All Records"
        type: integer
    responses:
      200:
        $ref: '#/responses/200'
      401:
        $ref: '#/responses/401'
      403:
        $ref: '#/responses/403'
      404:
        $ref: '#/responses/404'
      406:
        $ref: '#/responses/406'



  post:
    tags:
      - "Project"
    summary: "New Project"

    parameters:
      - in: body
        name: body
        required: true
        schema:
          type: ojbect
          properties:
            - name
            - description
          required:
            - name
          example:
            name: "project_test"
            description: 'test project description'
    responses:
      200:
        $ref: '#/responses/200'
      401:
        $ref: '#/responses/401'
      403:
        $ref: '#/responses/403'
      404:
        $ref: '#/responses/404'
      406:
        $ref: '#/responses/406'


/project/{id}/:
  get:
    tags:
      - "Project"
    summary: "Get By Id"
    parameters:
      - in: path
        name: id
        required: true
        example: 1
        description: "id"
        type: integer
    responses:
      200:
        $ref: '#/responses/200'
      401:
        $ref: '#/responses/401'
      403:
        $ref: '#/responses/403'
      404:
        $ref: '#/responses/404'
      406:
        $ref: '#/responses/406'

  delete:
    tags:
      - "Project"
    summary: "Delete by id"
    parameters:
      - in: path
        name: id
        required: true
        example: 1
        description: "id"
        type: integer
    responses:
      200:
        $ref: '#/responses/200'
      401:
        $ref: '#/responses/401'
      403:
        $ref: '#/responses/403'
      404:
        $ref: '#/responses/404'
      406:
        $ref: '#/responses/406'


  put:
    tags:
      - "Project"
    summary: "Update Project"
    parameters:
      - in: path
        name: id
        required: true
        example: 1
        description: "id"
        type: integer
      - in: body
        name: body
        required: true
        schema:
          type: ojbect
          properties:
            - name
            - description
          required:
            - name
          example:
            name: "project_test2"
            description: 'test project description edited'
    responses:
      200:
        $ref: '#/responses/200'
      401:
        $ref: '#/responses/401'
      403:
        $ref: '#/responses/403'
      404:
        $ref: '#/responses/404'
      406:
        $ref: '#/responses/406'
